apiVersion: v1
kind: Pod
metadata:
  name: init-example
  labels:
    app: init-example
spec:
  containers:
  - name: nginx
    image: nginx:1.12.2
    ports:
    - containerPort: 80
    volumeMounts:
    - name: data
      mountPath: /usr/share/nginx/html
  - name: logrotate
    image: blacklabelops/logrotate:1.2
    env:
    - name: LOG_DIRECTORIES
      value: "/data"
    - name: LOGROTATE_INTERVAL
      value: "hourly"
    volumeMounts:
    - name: data
      mountPath: /data
  initContainers:
  - name: debian
    image: debian
    volumeMounts:
    - name: data
      mountPath: /data
    command: ["/bin/sh"]
    args: ["-c", "echo Hello from Kubernetes TAW > /data/index.html"]
  volumes:
    - name: data
      emptyDir: {}
