apiVersion: v1
kind: Pod
metadata:
  name: init-example
spec:
  containers:
  - name: nginx
    image: nginx:1.12.2
    ports:
    - containerPort: 80
    volumeMounts:
    - name: logs
      mountPath: /var/logs/nginx
    - name: html
      mountPath: /usr/share/nginx/html
  - name: logrotate
    image: blacklabelops/logrotate:1.2
    env:
    - name: LOG_DIRECTORIES
      value: "/logs"
    - name: LOGROTATE_INTERVAL
      value: "hourly"
    volumeMounts:
    - name: logs
      mountPath: /logs
  initContainers:
  - name: debian
    image: debian
    volumeMounts:
    - name: html
      mountPath: /html
    command: ["/bin/sh"]
    args: ["-c", "echo Hello from Kubernetes TAW > /html/index.html"]
  volumes:
    - name: logs
      emptyDir: {}
    - name: html
      emptyDir: {}
