apiVersion: v1
kind: Pod
metadata:
  name: sidecar-example
spec:
  containers:
  - name: nginx
    image: nginx:1.12.2
    ports:
    - containerPort: 80
    volumeMounts:
    - name: logs
      mountPath: /var/log/nginx
  - name: logrotate
    image: blacklabelops/logrotate:1.2
    env:
    - name: LOG_DIRECTORIES
      value: "/logs"
    - name: LOGROTATE_INTERVAL
      value: "hourly"
    volumeMounts:
    - name: logs
      mountPath: /logs
  volumes:
    - name: logs
      emptyDir: {}
